### ISSUE TITLE
Can't start /web. What could be the thing? 

### ISSUE THREAD

**Issue by Vandeko1** [atulmy/crate#13]
`ERROR in ./src/ui/input/File.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: Object.values is not a function
    at PluginPass.JSXOpeningElement (D:\crate\code\web\node_modules\styled-jsx\dist\babel.js:39:139)
    at newFn (D:\crate\code\web\node_modules\@babel\traverse\lib\visitors.js:193:21)
    at NodePath._call (D:\crate\code\web\node_modules\@babel\traverse\lib\path\context.js:53:20)
    at NodePath.call (D:\crate\code\web\node_modules\@babel\traverse\lib\path\context.js:40:17)
    at NodePath.visit (D:\crate\code\web\node_modules\@babel\traverse\lib\path\context.js:88:12)
    at TraversalContext.visitQueue (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitSingle (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:90:19)
    at TraversalContext.visit (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:146:19)
    at Function.traverse.node (D:\crate\code\web\node_modules\@babel\traverse\lib\index.js:94:17)
    at NodePath.visit (D:\crate\code\web\node_modules\@babel\traverse\lib\path\context.js:95:18)
    at TraversalContext.visitQueue (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitMultiple (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:85:17)
    at TraversalContext.visit (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:144:19)
    at Function.traverse.node (D:\crate\code\web\node_modules\@babel\traverse\lib\index.js:94:17)
    at NodePath.visit (D:\crate\code\web\node_modules\@babel\traverse\lib\path\context.js:95:18)
    at TraversalContext.visitQueue (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitMultiple (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:85:17)
    at TraversalContext.visit (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:144:19)
    at Function.traverse.node (D:\crate\code\web\node_modules\@babel\traverse\lib\index.js:94:17)
    at NodePath.visit (D:\crate\code\web\node_modules\@babel\traverse\lib\path\context.js:95:18)
    at TraversalContext.visitQueue (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitMultiple (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:85:17)
    at TraversalContext.visit (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:144:19)
    at Function.traverse.node (D:\crate\code\web\node_modules\@babel\traverse\lib\index.js:94:17)
    at NodePath.visit (D:\crate\code\web\node_modules\@babel\traverse\lib\path\context.js:95:18)
    at TraversalContext.visitQueue (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:118:16)
    at TraversalContext.visitSingle (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:90:19)
    at TraversalContext.visit (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:146:19)
    at Function.traverse.node (D:\crate\code\web\node_modules\@babel\traverse\lib\index.js:94:17)
    at NodePath.visit (D:\crate\code\web\node_modules\@babel\traverse\lib\path\context.js:95:18)
 @ ./src/ui/input/index.js 5:0-26 6:0-41
 @ ./src/modules/admin/crate/CreateOrEdit.js
 @ ./src/setup/routes/admin/crate.js
 @ ./src/setup/routes/admin/index.js
 @ ./src/setup/routes/index.js
 @ ./src/setup/client/App.js
 @ ./src/setup/client/index.js`

Also /mobile not installed 
`npm ERR! cb() never called!`
(I try on CMD and BASH on Windows 10x64)

**Comment by Vandeko1** [comment]
> `ERROR in ./src/ui/input/File.js Module build failed (from ./node_modules/babel-loader/lib/index.js): TypeError: Object.values is not a function at PluginPass.JSXOpeningElement (D:\crate\code\web\node_modules\styled-jsx\dist\babel.js:39:139) at newFn (D:\crate\code\web\node_modules\@babel\traverse\lib\visitors.js:193:21) at NodePath._call (D:\crate\code\web\node_modules\@babel\traverse\lib\path\context.js:53:20) at NodePath.call (D:\crate\code\web\node_modules\@babel\traverse\lib\path\context.js:40:17) at NodePath.visit (D:\crate\code\web\node_modules\@babel\traverse\lib\path\context.js:88:12) at TraversalContext.visitQueue (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:118:16) at TraversalContext.visitSingle (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:90:19) at TraversalContext.visit (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:146:19) at Function.traverse.node (D:\crate\code\web\node_modules\@babel\traverse\lib\index.js:94:17) at NodePath.visit (D:\crate\code\web\node_modules\@babel\traverse\lib\path\context.js:95:18) at TraversalContext.visitQueue (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:118:16) at TraversalContext.visitMultiple (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:85:17) at TraversalContext.visit (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:144:19) at Function.traverse.node (D:\crate\code\web\node_modules\@babel\traverse\lib\index.js:94:17) at NodePath.visit (D:\crate\code\web\node_modules\@babel\traverse\lib\path\context.js:95:18) at TraversalContext.visitQueue (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:118:16) at TraversalContext.visitMultiple (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:85:17) at TraversalContext.visit (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:144:19) at Function.traverse.node (D:\crate\code\web\node_modules\@babel\traverse\lib\index.js:94:17) at NodePath.visit (D:\crate\code\web\node_modules\@babel\traverse\lib\path\context.js:95:18) at TraversalContext.visitQueue (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:118:16) at TraversalContext.visitMultiple (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:85:17) at TraversalContext.visit (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:144:19) at Function.traverse.node (D:\crate\code\web\node_modules\@babel\traverse\lib\index.js:94:17) at NodePath.visit (D:\crate\code\web\node_modules\@babel\traverse\lib\path\context.js:95:18) at TraversalContext.visitQueue (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:118:16) at TraversalContext.visitSingle (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:90:19) at TraversalContext.visit (D:\crate\code\web\node_modules\@babel\traverse\lib\context.js:146:19) at Function.traverse.node (D:\crate\code\web\node_modules\@babel\traverse\lib\index.js:94:17) at NodePath.visit (D:\crate\code\web\node_modules\@babel\traverse\lib\path\context.js:95:18) @ ./src/ui/input/index.js 5:0-26 6:0-41 @ ./src/modules/admin/crate/CreateOrEdit.js @ ./src/setup/routes/admin/crate.js @ ./src/setup/routes/admin/index.js @ ./src/setup/routes/index.js @ ./src/setup/client/App.js @ ./src/setup/client/index.js`
> 
> Also /mobile not installed
> `npm ERR! cb() never called!`
> (I try on CMD and BASH on Windows 10x64)

I has Node v6. Update to v8 fix this problem.

**Comment by atulmy** [comment]
Please use latest LTS version (`8.12.0`) of Node .

**Comment by Vandeko1** [comment]
> Please use latest LTS version (`8.12.0`) of Node 

> Please use latest LTS version (`8.12.0`) of Node .

Thank you, it helped.
